# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NHM Informatics Lab
email: bioinf@nhm.ac.uk
description: "<p>The informatics team is inventing new digital tools for measuring, recording and explaining the natural world.</p><p>The Museums 79 million specimens and diverse research programme generate a vast amount of biodiversity data. We are structuring this information and developing digital tools to analyse, exchange and communicate the data with a global audience.</p>"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: informaticians

# Build settings
markdown: kramdown